time:
    # A timezone in the common 3 letter acronym and if daylight savings time should be used
    timezone: 'MST'
    use_daylight_savings: True

    # The start and end times in a string format
    start: '8:00'
    end: '17:00'

    # The min and max times to wait after an exercise to post the next one
    min_time_between: 50
    max_time_between: 75

notification:
    # The webhook URL for a slack integration
    webhook_url: ''

exercises:
    plank:
        name: 'Plank'
        unit: 'second'
        lower_bound: 20
        upper_bound: 50

